    MRF.correctBoundaryVelocity(U);

    fvVectorMatrix UEqn
    (
        fvm::ddt(rho, U) + fvm::div(rhoPhi, U)
      + MRF.DDt(rho, U)
      + turbulence->divDevRhoReff(rho, U)
     ==
        fvOptions(rho, U)
    );

    UEqn.relax();

    fvOptions.constrain(UEqn);

    if (pimple.momentumPredictor())
    {
        solve
        (
            UEqn
         ==
            fvc::reconstruct
            (
                (
                    // mixture.surfaceTensionForce()
                    // sigma*fvc::snGrad(psi)*fvc::interpolate(C)*fvc::interpolate(delta)
                  - fvc::interpolate(alpha1)*fvc::snGrad((lambda/pow(epsilon, 2))*(pow(alpha1, 3) - alpha1) - lambda*fvc::laplacian(alpha1))
                  - ghf*fvc::snGrad(rho)
                  - fvc::snGrad(p_rgh)
                ) * mesh.magSf()
            )
        );

        fvOptions.correct(U);
    }
